### ISSUE TITLE
Booth Elements

### ISSUE THREAD

**Issue by jcstraley** [aulitech/auli_site#61]
##Subtasks

- [ ] Freeman Services - table 30" x 72", 2 chair, wastebasket
- [ ]  75" Screen/TV (video loop only)
- [ ]  45" Screen/TV (Video loop only)
- [ ]  Bistro Table (30"x4')
- [ ]  Business Cards - (everyone for their own)
- [ ]  Background/Drape for table ??
- [ ]  PopUp Signage??
- [ ]  Visitor Info QR (3D) - Other??
- [ ]  Foam Board Posters (1 per Day??)
- [ ]  Video 1
- [ ]  Video 2
- [ ]  Video 3 (Beta testimonials)
- [ ]  Flyer (see Booth tab)
- [ ]  PACKAGING for giveaways
- [ ]  Polo Shirts
- [ ]  Website Update
- [ ]  Website NEWS page
